// Generated by gencpp from file electronics/rover.msg
// DO NOT EDIT!


#ifndef ELECTRONICS_MESSAGE_ROVER_H
#define ELECTRONICS_MESSAGE_ROVER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>
#include <std_msgs/Float64.h>
#include <geometry_msgs/Pose.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Time.h>

namespace electronics
{
template <class ContainerAllocator>
struct rover_
{
  typedef rover_<ContainerAllocator> Type;

  rover_()
    : velocity()
    , distance()
    , position()
    , battery()
    , time_running()  {
    }
  rover_(const ContainerAllocator& _alloc)
    : velocity(_alloc)
    , distance(_alloc)
    , position(_alloc)
    , battery(_alloc)
    , time_running(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _distance_type;
  _distance_type distance;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _battery_type;
  _battery_type battery;

   typedef  ::std_msgs::Time_<ContainerAllocator>  _time_running_type;
  _time_running_type time_running;





  typedef boost::shared_ptr< ::electronics::rover_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::electronics::rover_<ContainerAllocator> const> ConstPtr;

}; // struct rover_

typedef ::electronics::rover_<std::allocator<void> > rover;

typedef boost::shared_ptr< ::electronics::rover > roverPtr;
typedef boost::shared_ptr< ::electronics::rover const> roverConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::electronics::rover_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::electronics::rover_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::electronics::rover_<ContainerAllocator1> & lhs, const ::electronics::rover_<ContainerAllocator2> & rhs)
{
  return lhs.velocity == rhs.velocity &&
    lhs.distance == rhs.distance &&
    lhs.position == rhs.position &&
    lhs.battery == rhs.battery &&
    lhs.time_running == rhs.time_running;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::electronics::rover_<ContainerAllocator1> & lhs, const ::electronics::rover_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace electronics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::electronics::rover_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::electronics::rover_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::electronics::rover_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::electronics::rover_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::electronics::rover_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::electronics::rover_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::electronics::rover_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88cdce70f8f92a71fa841fa7b7186ec4";
  }

  static const char* value(const ::electronics::rover_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88cdce70f8f92a71ULL;
  static const uint64_t static_value2 = 0xfa841fa7b7186ec4ULL;
};

template<class ContainerAllocator>
struct DataType< ::electronics::rover_<ContainerAllocator> >
{
  static const char* value()
  {
    return "electronics/rover";
  }

  static const char* value(const ::electronics::rover_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::electronics::rover_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist velocity\n"
"std_msgs/Float64 distance\n"
"geometry_msgs/Pose position\n"
"std_msgs/Int32 battery\n"
"std_msgs/Time time_running\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
"================================================================================\n"
"MSG: std_msgs/Time\n"
"time data\n"
;
  }

  static const char* value(const ::electronics::rover_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::electronics::rover_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.distance);
      stream.next(m.position);
      stream.next(m.battery);
      stream.next(m.time_running);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rover_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::electronics::rover_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::electronics::rover_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "distance: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.distance);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "battery: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.battery);
    s << indent << "time_running: ";
    s << std::endl;
    Printer< ::std_msgs::Time_<ContainerAllocator> >::stream(s, indent + "  ", v.time_running);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ELECTRONICS_MESSAGE_ROVER_H
